<?xml version="1.0" encoding="UTF-8"?>

<!-- Esercizio: dtd interna ad un file xml-->
<!DOCTYPE TEI [
    <!ELEMENT TEI (header,facsimile?,testo+)> 
    <!ELEMENT header (#PCDATA)>  
    <!ELEMENT facsimile (#PCDATA)>      
    <!ELEMENT testo (#PCDATA|seg)*> 
    <!ELEMENT seg (#PCDATA)>

    <!ATTLIST header 
    type CDATA #FIXED "intestazione"
    lang NMTOKEN #IMPLIED>
    <!ATTLIST facsimile
    source CDATA #REQUIRED
    ref IDREFS #IMPLIED>
    <!ATTLIST testo
    id ID #REQUIRED
    type CDATA #IMPLIED>
]>

<TEI>
    <header type="intestazione" lang="IT"> 
        contenuto testuale dell'elemento header 
    </header>
    <facsimile source="facsimilesource" ref="x"> 
        contenuto testuale dell'elemento header
    </facsimile>
    <testo id="x" type="description"> 
        <seg>
            contenuto testuale dell'elemento seg
        </seg>
            contenuto testuale dell'elemento testo
    </testo>
</TEI>